[pytest]
testpaths = bdd
python_files = test_*.py
addopts = -s --tb=short --browser-channel chrome --timeout=120 --tracing off --output output/screenshots
filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning
    ignore::UserWarning

[tool:pytest]
# Configuração do Playwright
playwright_browser = chromium
playwright_headless = true
